sudo: false

language:
    - php
    - node_js

php:
    - 7.0

before_install:
    - source .tests/bin/universal-environment-vars.sh
    - echo $UNICI_PROJECT_DIRECTORY

script:
    - exit 0;

notifications:
    email: false
