sudo: false

language:
    - php
    - node_js

php:
    - 7.0

before_install:
    - source .tests/bin/universal-environment-vars.sh

install:
    - composer install
    - source .tests/bin/install.sh

script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpcs --standard=phpcs.ruleset.xml . -p

notifications:
    email: false
