sudo: false

language:
    - php
    - node_js

php:
    - 7.0

before_install:
    - source .tests/bin/universal-environment-vars.sh

install:
    - source .tests/bin/install.sh
    - ls -lah $UNICI_TMPDIR
    - ls -lah $UNICI_TMPDIR/wpcore
    - ls -lah $UNICI_TMPDIR/wpdevel

script:
    - exit 0;

notifications:
    email: false
