# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0
      # - image: circleci/mysql:5.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Set Environment Variables"
          command: |
            bash .tests/bin/universal-environment-vars.sh
            source $BASH_ENV
      - run:
          name: "Test Environment Variables"
          command: |
            echo $UNICI_PROJECT_DIRECTORY
